# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          key: lib
          path: lib
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ant -noinput
      - uses: actions/upload-artifact@v2
        with:
          name: config # don't add .zip extension!
          path: build/config.zip
      - uses: AButler/upload-release-assets@v2.0
        if: github.event_name == 'release'
        with:
          files: build/config.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
name: XSLT CI
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  release:
    types: [ published ]
